[workspace]
resolver = "2"

members = [
    "break_stack",
    "break_stack_macros",
    "testing",
    "examples/*",
]

default-members = [
    "break_stack",
    "break_stack_macros",
    "testing",
]
